Repository RyoNkmr/stuck-js, pull requests merged in 2018-06, with the labels that each got.

#5 support initially hidden contents
  .gitignore
  .npmignore
  .vscode/settings.json
  docs/index.js
  lib/index.js
  lib/index.js.gz
  package.json
  specs/stuck.spec.js
  src/placeholder.js
  src/sticky.js
Labels: enhancement

#6 update README
  README.md
  package-lock.json
  package.json
Labels: good first issue, wontfix

#9 support dynamically page height changing
  .eslintrc.js
  docs/index.js
  lib/index.js
  lib/index.js.gz
  specs/sticky.spec.js
  src/sticky.js
Labels: enhancement

#13 #11 and #12 Fix placeholder sizing on resize
  .npmignore
  docs/fullwidth.html
  docs/index.js
  docs/initially-hidden.html
  lib/index.js
  lib/index.js.gz
  package-lock.json
  package.json
  specs/puppeteerHelper.js
  specs/sticky.spec.js
  specs/stuck.spec.js
  src/placeholder.js
  src/sticky.js
  src/stuck.js
  webpack.config.development.js
  webpack.config.js
Labels: bug, enhancement

#18 fix ignoring falsy placehold
  docs/index.js
  lib/index.js
  lib/index.js.gz
  specs/stuck.spec.js
  src/placeholder.js
Labels: bug
